<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUGhxPy2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUGhxPy2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUGhxPy2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUGhxPy2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUGhxPy2\App_KernelDevDebugContainer([
    'container.build_hash' => 'UGhxPy2',
    'container.build_id' => 'cbbdcfdf',
    'container.build_time' => 1700828361,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUGhxPy2');
