<?php

namespace ContainerUGhxPy2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qy1KlibService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qy1Klib' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qy1Klib'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminControler::setWordOfTheDay' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CalendarController::showCalendar' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\FriendController::acceptFriendRequest' => ['privates', '.service_locator.sBWrfhO', 'get_ServiceLocator_SBWrfhOService', true],
            'App\\Controller\\FriendController::addFriend' => ['privates', '.service_locator.sBWrfhO', 'get_ServiceLocator_SBWrfhOService', true],
            'App\\Controller\\FriendController::declineFriendRequest' => ['privates', '.service_locator.sBWrfhO', 'get_ServiceLocator_SBWrfhOService', true],
            'App\\Controller\\FriendController::pendingFriendRequests' => ['privates', '.service_locator.0txdB0f', 'get_ServiceLocator_0txdB0fService', true],
            'App\\Controller\\FriendController::showFriends' => ['privates', '.service_locator.0txdB0f', 'get_ServiceLocator_0txdB0fService', true],
            'App\\Controller\\GameController::congratulations' => ['privates', '.service_locator.x.rs099', 'get_ServiceLocator_X_Rs099Service', true],
            'App\\Controller\\GameController::index' => ['privates', '.service_locator.x.rs099', 'get_ServiceLocator_X_Rs099Service', true],
            'App\\Controller\\GameController::lost' => ['privates', '.service_locator.x.rs099', 'get_ServiceLocator_X_Rs099Service', true],
            'App\\Controller\\GestionController::userAvatar' => ['privates', '.service_locator.A0o8nYx', 'get_ServiceLocator_A0o8nYxService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminControler:setWordOfTheDay' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CalendarController:showCalendar' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\FriendController:acceptFriendRequest' => ['privates', '.service_locator.sBWrfhO', 'get_ServiceLocator_SBWrfhOService', true],
            'App\\Controller\\FriendController:addFriend' => ['privates', '.service_locator.sBWrfhO', 'get_ServiceLocator_SBWrfhOService', true],
            'App\\Controller\\FriendController:declineFriendRequest' => ['privates', '.service_locator.sBWrfhO', 'get_ServiceLocator_SBWrfhOService', true],
            'App\\Controller\\FriendController:pendingFriendRequests' => ['privates', '.service_locator.0txdB0f', 'get_ServiceLocator_0txdB0fService', true],
            'App\\Controller\\FriendController:showFriends' => ['privates', '.service_locator.0txdB0f', 'get_ServiceLocator_0txdB0fService', true],
            'App\\Controller\\GameController:congratulations' => ['privates', '.service_locator.x.rs099', 'get_ServiceLocator_X_Rs099Service', true],
            'App\\Controller\\GameController:index' => ['privates', '.service_locator.x.rs099', 'get_ServiceLocator_X_Rs099Service', true],
            'App\\Controller\\GameController:lost' => ['privates', '.service_locator.x.rs099', 'get_ServiceLocator_X_Rs099Service', true],
            'App\\Controller\\GestionController:userAvatar' => ['privates', '.service_locator.A0o8nYx', 'get_ServiceLocator_A0o8nYxService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminControler::setWordOfTheDay' => '?',
            'App\\Controller\\CalendarController::showCalendar' => '?',
            'App\\Controller\\FriendController::acceptFriendRequest' => '?',
            'App\\Controller\\FriendController::addFriend' => '?',
            'App\\Controller\\FriendController::declineFriendRequest' => '?',
            'App\\Controller\\FriendController::pendingFriendRequests' => '?',
            'App\\Controller\\FriendController::showFriends' => '?',
            'App\\Controller\\GameController::congratulations' => '?',
            'App\\Controller\\GameController::index' => '?',
            'App\\Controller\\GameController::lost' => '?',
            'App\\Controller\\GestionController::userAvatar' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminControler:setWordOfTheDay' => '?',
            'App\\Controller\\CalendarController:showCalendar' => '?',
            'App\\Controller\\FriendController:acceptFriendRequest' => '?',
            'App\\Controller\\FriendController:addFriend' => '?',
            'App\\Controller\\FriendController:declineFriendRequest' => '?',
            'App\\Controller\\FriendController:pendingFriendRequests' => '?',
            'App\\Controller\\FriendController:showFriends' => '?',
            'App\\Controller\\GameController:congratulations' => '?',
            'App\\Controller\\GameController:index' => '?',
            'App\\Controller\\GameController:lost' => '?',
            'App\\Controller\\GestionController:userAvatar' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
